const dershanelerlgs = [
    {
        id: "kuzey-kurs-vip",
        isim: "Kuzey Kurs VIP",
        ucret8: 90000,
        ucret7: 70000,
        konum: "Kadıköy",
        slogan: "En İyi Eğitim İçin Kuzey Kurs VIP",
        tanitimVideosu: "https://www.example.com/kuzey-video",
        basariTablosu: "https://www.example.com/kuzey-basari",
        etutSaatleri: "Hafta içi 16.30-18.50 / Haftasonu 09.00-18.00",
        sinifMevcudu: "6-8 öğrenci",
        aylikDersSayisi: "7.sınıf 10+6, 8.sınıf 10+6",
        aylikDenemeSayisi: 50,
        dersKaynaklari: "BES, Dijidemi Sistem, ÜçDörtBeş Yayınları, Hız Yayınları, Sinan Kuzucu Yayınları, Fenomen Yayınları.",
        egitmenKadrosu: "Matematik öğretmeni 15 sene, fizik 12 sene, Türkçe 5 ve 7 sene, Tarih ve Coğrafya 9, Kimya 8 sene.",
        ekBilgiler: "Öğrenciyle bire bir özel ders + koçluk sistemi + öğrenci performansını sıkı takip + yapay zeka destekli soru havuzu + kafes yöntemiyle eğitim.",
        logo: "icon.jpeg",
        detaySayfa: "dershane.html?id=kuzey-kurs-vip",
        hazirlik: ["LGS"],
        kazanımDegerlendirmeSinavi: "<a href='kuzeykazanim.pdf' target='_blank'>Kazanım Değerlendirme Sınavı PDF</a>"
    }
    ,
    {
        id: "radikal-egitim-kurumlari",
        isim: "Radikal Eğitim Kurumları",
        ucret8: 100000,
        ucret7: 90000,
        konum: "Osmanağa, Vahap Bey Sk. No:19, 34734 Kadıköy/İstanbul",
        slogan: "Çalışır çalıştırır kazandırır",
        tanitimVideosu: "https://www.example.com/radikal-video",
        basariTablosu: "https://www.example.com/radikal-basari",
        etutSaatleri: "(8.sınıf) Cumartesi-Pazar: 08.30-13.30 + Perşembe 17.15-19.25, (7.sınıf) Cumartesi-Pazar 14.00-18.00",
        sinifMevcudu: "10 öğrenci",
        aylikDersSayisi: "7.Sınıflar 12 Ders+2 birebir (Yıllık Maksimum 60), 8.Sınıflar 15 Ders+3 birebir (Yıllık Maksimum 80)",
        aylikDenemeSayisi: "50 deneme (8.sınıflar için), 30-35 deneme (7.sınıflar için)",
        dersKaynaklari: "Radikal Yayınları, Nartest Yayınları, Ankara Yayınları, Nego Yayınları, Özdebir, Soru Akademisi, Tudem, Paraf Yayınları…",
        egitmenKadrosu: "Minimum 5-6 yıl tecrübeli öğretmenler.",
        ekBilgiler: "YKS ve KPSS için rehberlik servisi, Raki-Koç (öğrenci takip sistemi) ile öğrenciye özel kitap, kafes yöntemi (soru bankası), bireysel soru çözümü, Atölye eğitimi (öğrencinin eksikleri için, Oksijen Ders (temel matematik, problemler, paragraf, hızlı okuma dersleri)).",
        logo: "icon.jpeg",
        detaySayfa: "dershane.html?id=radikal-egitim-kurumlari",
        hazirlik: ["LGS"] // LGS ve YKS hazırlık
    },
    {
        id: "murat-egitim-vip",
        isim: "Murat Eğitim VIP",
        ucret8: 85000,
        ucret7: 75000,
        konum: "Kadıköy",
        slogan: "Eğitim yolundaki en iyi adımınız",
        tanitimVideosu: "https://www.example.com/murat-video",
        basariTablosu: "https://www.example.com/murat-basari",
        etutSaatleri: "Hafta içi 16.30-19.20",
        sinifMevcudu: "10-12 öğrenci",
        aylikDersSayisi: "Haftalık 16 Saat",
        aylikDenemeSayisi: 50,
        dersKaynaklari: "Muba Yayınları, Fenomen yayınları",
        egitmenKadrosu: "Minimum ortalama 10-15 yıllık tecrübeli öğretmenler.",
        ekBilgiler: "Koçluk + Rehberlik, Birebir, Etüt",
        logo: "icon.jpeg",
        detaySayfa: "dershane.html?id=murat-egitim-vip",
        hazirlik: ["LGS"]
    },
    {
        id: "edukentvip",
        isim: "Edukentvip",
        ucret8: 100000,
        ucret7: null,
        konum: "Osmanağa, Osmanağa Mah. Söğütlüçeşme Cad, Nal Sk. No:5, 34714 Kadıköy/İstanbul",
        slogan: "Başarı merdivenin de ki en güvenli basamağınız.",
        tanitimVideosu: "https://www.example.com/edukentvip-video",
        basariTablosu: "https://www.example.com/edukentvip-basari",
        etutSaatleri: "Hafta İçi 17.00-19.15 / Hafta Sonu 14.30-17.00",
        sinifMevcudu: "10-12 öğrenci",
        aylikDersSayisi: "Haftalık 14 saat",
        aylikDenemeSayisi: 50,
        dersKaynaklari: "Mozaik Yayınları, Hız Yayınları, Edukent Yayınları.",
        egitmenKadrosu: "15-20 yıl deneyimli öğretmenler",
        ekBilgiler: "İşler Kitap Evinin tüm kaynaklarına ulaşma, imkanı uygulama ile öğrencilere soru ulaştırma ve denemelerini takip etme programı.",
        logo: "icon.jpeg",
        detaySayfa: "dershane.html?id=edukentvip",
        hazirlik: ["LGS"] 
    },
    {
        id: "aydin-kurs",
        isim: "Aydın Kurs",
        ucret8: 80000,
        ucret7: null,
        konum: "Osmanağa, Halitağa Cd. NO:14, 34714 Kadıköy/İstanbul",
        slogan: "Eğitimde kalite, gelecekte başarı.",
        tanitimVideosu: "https://www.example.com/aydin-video",
        basariTablosu: "https://www.example.com/aydin-basari",
        etutSaatleri: "Cumartesi 10.40-13.00, Pazar 14.00-16.20",
        sinifMevcudu: "10-12 öğrenci",
        aylikDersSayisi: "Haftalık 13 saat ders",
        aylikDenemeSayisi: "60 deneme (8.sınıflar), 30 deneme (7.sınıflar)",
        dersKaynaklari: "Miray Yayınları, Aydın Yayınları",
        egitmenKadrosu: "Her biri kendi alanında en az 7 yıl deneyimli öğretmenler.",
        ekBilgiler: "Koçluk Sistemi + Rehberlik, sınırsız özel (birebir) dersler, e12 sistemi, etütler (kafes + ofis yöntemleri)",
        logo: "icon.jpeg",
        detaySayfa: "dershane.html?id=aydin-kurs",
        hazirlik: ["LGS"] 
    },
    {
        id: "ender-egitim",
        isim: "Ender Eğitim",
        ucret8: 30000,
        ucret7: null,
        konum: "Yukarı Dudullu, Şenol Sk. No; 16/1-2, 34775 Dudullu/Ümraniye/İstanbul",
        slogan: "Başarı sizden destek bizden",
        tanitimVideosu: "https://www.example.com/ender-video",
        basariTablosu: "https://www.example.com/ender-basari",
        etutSaatleri: "Cumartesi-Pazar 08.30-13.30 / 14.00-17.20, Pazartesi-Salı-Çarşamba-Perşembe: 16.00-19.20",
        sinifMevcudu: "14-16 öğrenci",
        aylikDersSayisi: "",
        aylikDenemeSayisi: 30,
        dersKaynaklari: "Fenomen Yayınları, Orjinal Yayınları, Hız Yayınları, Nartest Yayınları, Ankara Yayınları…",
        egitmenKadrosu: "Her biri kendi alanında en az 7 yıl deneyimli öğretmenler.",
        ekBilgiler: "Koçluk Sistemi + Rehberlik sistemi, etütler",
        logo: "icon.jpeg",
        detaySayfa: "dershane.html?id=ender-egitim",
        hazirlik: ["LGS"] 
    },
    {
        id: "sinav-dershanesi",
        isim: "Sınav Dershanesi",
        ucret8: 95000,
        ucret7: 80000,
        konum: "Osmanağa, Halitağa Cd. NO:17, 34714 Kadıköy/İstanbul",
        slogan: "En iyi eğitimin adresi",
        tanitimVideosu: "https://www.example.com/sinav-video",
        basariTablosu: "https://www.example.com/sinav-basari",
        etutSaatleri: "Hafta içi-hafta sonu birebir soru çözümleri, puzzle eksik tamamlama 10.00-18.00",
        sinifMevcudu: "8-10 öğrenci",
        aylikDersSayisi: "7.Sınıflar 15+3, 8.Sınıflar 15+3+3",
        aylikDenemeSayisi: "52 deneme (8.sınıflar), 25 deneme (7.sınıflar)",
        dersKaynaklari: "Sınav Yayınları, 345 All Star Yayınları, Töder Yayınları",
        egitmenKadrosu: "Her biri kendi alanında en az 8 yıl deneyimli Sınav Genel Merkezinin görevlendirdiği öğretmenler.",
        ekBilgiler: "Kişiye özel kitap, 345 All Star öğretmenleriyle soru çözümü, sınıf kampları, sınav analizleri.",
        logo: "icon.jpeg",
        detaySayfa: "dershane.html?id=sinav-dershanesi",
        hazirlik: ["LGS"] 
    }
];
const dershaneleryks = [
    {



    }]


const dershaneler = [
    {
        id: "kuzey-kurs-vip",
        isim: "Kuzey Kurs VIP",
        ucret8: 90000,
        ucret7: 70000,
        konum: "Kadıköy",
        slogan: "En İyi Eğitim İçin Kuzey Kurs VIP",
        tanitimVideosu: "https://www.example.com/kuzey-video",
        basariTablosu: "https://www.example.com/kuzey-basari",
        etutSaatleri: "Hafta içi 16.30-18.50 / Haftasonu 09.00-18.00",
        sinifMevcudu: "6-8 öğrenci",
        aylikDersSayisi: "7.sınıf 10+6, 8.sınıf 10+6",
        aylikDenemeSayisi: 50,
        dersKaynaklari: "BES, Dijidemi Sistem, ÜçDörtBeş Yayınları, Hız Yayınları, Sinan Kuzucu Yayınları, Fenomen Yayınları.",
        egitmenKadrosu: "Matematik öğretmeni 15 sene, fizik 12 sene, Türkçe 5 ve 7 sene, Tarih ve Coğrafya 9, Kimya 8 sene.",
        ekBilgiler: "Öğrenciyle bire bir özel ders + koçluk sistemi + öğrenci performansını sıkı takip + yapay zeka destekli soru havuzu + kafes yöntemiyle eğitim.",
        logo: "icon.jpeg",
        detaySayfa: "dershane.html?id=kuzey-kurs-vip",
        hazirlik: ["LGS"],
        kazanımDegerlendirmeSinavi: "<a href='kuzeykazanim.pdf' target='_blank'>Kazanım Değerlendirme Sınavı PDF</a>"
    }
    ,
    {
        id: "radikal-egitim-kurumlari",
        isim: "Radikal Eğitim Kurumları",
        ucret8: 100000,
        ucret7: 90000,
        konum: "Osmanağa, Vahap Bey Sk. No:19, 34734 Kadıköy/İstanbul",
        slogan: "Çalışır çalıştırır kazandırır",
        tanitimVideosu: "https://www.example.com/radikal-video",
        basariTablosu: "https://www.example.com/radikal-basari",
        etutSaatleri: "(8.sınıf) Cumartesi-Pazar: 08.30-13.30 + Perşembe 17.15-19.25, (7.sınıf) Cumartesi-Pazar 14.00-18.00",
        sinifMevcudu: "10 öğrenci",
        aylikDersSayisi: "7.Sınıflar 12 Ders+2 birebir (Yıllık Maksimum 60), 8.Sınıflar 15 Ders+3 birebir (Yıllık Maksimum 80)",
        aylikDenemeSayisi: "50 deneme (8.sınıflar için), 30-35 deneme (7.sınıflar için)",
        dersKaynaklari: "Radikal Yayınları, Nartest Yayınları, Ankara Yayınları, Nego Yayınları, Özdebir, Soru Akademisi, Tudem, Paraf Yayınları…",
        egitmenKadrosu: "Minimum 5-6 yıl tecrübeli öğretmenler.",
        ekBilgiler: "YKS ve KPSS için rehberlik servisi, Raki-Koç (öğrenci takip sistemi) ile öğrenciye özel kitap, kafes yöntemi (soru bankası), bireysel soru çözümü, Atölye eğitimi (öğrencinin eksikleri için, Oksijen Ders (temel matematik, problemler, paragraf, hızlı okuma dersleri)).",
        logo: "icon.jpeg",
        detaySayfa: "dershane.html?id=radikal-egitim-kurumlari",
        hazirlik: ["LGS"] // LGS ve YKS hazırlık
    },
    {
        id: "murat-egitim-vip",
        isim: "Murat Eğitim VIP",
        ucret8: 85000,
        ucret7: 75000,
        konum: "Kadıköy",
        slogan: "Eğitim yolundaki en iyi adımınız",
        tanitimVideosu: "https://www.example.com/murat-video",
        basariTablosu: "https://www.example.com/murat-basari",
        etutSaatleri: "Hafta içi 16.30-19.20",
        sinifMevcudu: "10-12 öğrenci",
        aylikDersSayisi: "Haftalık 16 Saat",
        aylikDenemeSayisi: 50,
        dersKaynaklari: "Muba Yayınları, Fenomen yayınları",
        egitmenKadrosu: "Minimum ortalama 10-15 yıllık tecrübeli öğretmenler.",
        ekBilgiler: "Koçluk + Rehberlik, Birebir, Etüt",
        logo: "icon.jpeg",
        detaySayfa: "dershane.html?id=murat-egitim-vip",
        hazirlik: ["LGS"]
    },
    {
        id: "edukentvip",
        isim: "Edukentvip",
        ucret8: 100000,
        ucret7: null,
        konum: "Osmanağa, Osmanağa Mah. Söğütlüçeşme Cad, Nal Sk. No:5, 34714 Kadıköy/İstanbul",
        slogan: "Başarı merdivenin de ki en güvenli basamağınız.",
        tanitimVideosu: "https://www.example.com/edukentvip-video",
        basariTablosu: "https://www.example.com/edukentvip-basari",
        etutSaatleri: "Hafta İçi 17.00-19.15 / Hafta Sonu 14.30-17.00",
        sinifMevcudu: "10-12 öğrenci",
        aylikDersSayisi: "Haftalık 14 saat",
        aylikDenemeSayisi: 50,
        dersKaynaklari: "Mozaik Yayınları, Hız Yayınları, Edukent Yayınları.",
        egitmenKadrosu: "15-20 yıl deneyimli öğretmenler",
        ekBilgiler: "İşler Kitap Evinin tüm kaynaklarına ulaşma, imkanı uygulama ile öğrencilere soru ulaştırma ve denemelerini takip etme programı.",
        logo: "icon.jpeg",
        detaySayfa: "dershane.html?id=edukentvip",
        hazirlik: ["LGS"] 
    },
    {
        id: "aydin-kurs",
        isim: "Aydın Kurs",
        ucret8: 80000,
        ucret7: null,
        konum: "Osmanağa, Halitağa Cd. NO:14, 34714 Kadıköy/İstanbul",
        slogan: "Eğitimde kalite, gelecekte başarı.",
        tanitimVideosu: "https://www.example.com/aydin-video",
        basariTablosu: "https://www.example.com/aydin-basari",
        etutSaatleri: "Cumartesi 10.40-13.00, Pazar 14.00-16.20",
        sinifMevcudu: "10-12 öğrenci",
        aylikDersSayisi: "Haftalık 13 saat ders",
        aylikDenemeSayisi: "60 deneme (8.sınıflar), 30 deneme (7.sınıflar)",
        dersKaynaklari: "Miray Yayınları, Aydın Yayınları",
        egitmenKadrosu: "Her biri kendi alanında en az 7 yıl deneyimli öğretmenler.",
        ekBilgiler: "Koçluk Sistemi + Rehberlik, sınırsız özel (birebir) dersler, e12 sistemi, etütler (kafes + ofis yöntemleri)",
        logo: "icon.jpeg",
        detaySayfa: "dershane.html?id=aydin-kurs",
        hazirlik: ["LGS"] 
    },
    {
        id: "ender-egitim",
        isim: "Ender Eğitim",
        ucret8: 30000,
        ucret7: null,
        konum: "Yukarı Dudullu, Şenol Sk. No; 16/1-2, 34775 Dudullu/Ümraniye/İstanbul",
        slogan: "Başarı sizden destek bizden",
        tanitimVideosu: "https://www.example.com/ender-video",
        basariTablosu: "https://www.example.com/ender-basari",
        etutSaatleri: "Cumartesi-Pazar 08.30-13.30 / 14.00-17.20, Pazartesi-Salı-Çarşamba-Perşembe: 16.00-19.20",
        sinifMevcudu: "14-16 öğrenci",
        aylikDersSayisi: "",
        aylikDenemeSayisi: 30,
        dersKaynaklari: "Fenomen Yayınları, Orjinal Yayınları, Hız Yayınları, Nartest Yayınları, Ankara Yayınları…",
        egitmenKadrosu: "Her biri kendi alanında en az 7 yıl deneyimli öğretmenler.",
        ekBilgiler: "Koçluk Sistemi + Rehberlik sistemi, etütler",
        logo: "icon.jpeg",
        detaySayfa: "dershane.html?id=ender-egitim",
        hazirlik: ["LGS"] 
    },
    {
        id: "sinav-dershanesi",
        isim: "Sınav Dershanesi",
        ucret8: 95000,
        ucret7: 80000,
        konum: "Osmanağa, Halitağa Cd. NO:17, 34714 Kadıköy/İstanbul",
        slogan: "En iyi eğitimin adresi",
        tanitimVideosu: "https://www.example.com/sinav-video",
        basariTablosu: "https://www.example.com/sinav-basari",
        etutSaatleri: "Hafta içi-hafta sonu birebir soru çözümleri, puzzle eksik tamamlama 10.00-18.00",
        sinifMevcudu: "8-10 öğrenci",
        aylikDersSayisi: "7.Sınıflar 15+3, 8.Sınıflar 15+3+3",
        aylikDenemeSayisi: "52 deneme (8.sınıflar), 25 deneme (7.sınıflar)",
        dersKaynaklari: "Sınav Yayınları, 345 All Star Yayınları, Töder Yayınları",
        egitmenKadrosu: "Her biri kendi alanında en az 8 yıl deneyimli Sınav Genel Merkezinin görevlendirdiği öğretmenler.",
        ekBilgiler: "Kişiye özel kitap, 345 All Star öğretmenleriyle soru çözümü, sınıf kampları, sınav analizleri.",
        logo: "icon.jpeg",
        detaySayfa: "dershane.html?id=sinav-dershanesi",
        hazirlik: ["LGS"] 
    }
];
